# Nama workflow-mu
name: Scrape Harga Emas

on:
  # 1. Menjalankan setiap jam (menit ke-0, setiap jam)
  schedule:
    - cron: '0 * * * *'
  
  # 2. Tambahkan ini agar kamu bisa run manual dari tab Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Menggunakan server Linux dari GitHub

    steps:
      # 1. "Check out" atau ambil kodemu dari repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js di server
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Pakai Node.js versi 18

      # 3. Install semua library (axios, cheerio)
      - name: Install dependencies
        run: npm install

      # 4. JALANKAN SCRIPT-MU!
      - name: Run scraper
        run: node index.js

      # 5. Commit file harga-emas.json yang baru
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update harga emas otomatis'
          file_pattern: 'harga-emas.json' # Hanya commit file ini
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
